export const departuresList = [
  {
    id: 'id-1',
    terminal: 'A',
    localTime: '5:40',
    destination: 'Warsaw',
    status: 'Landed 5:52',
    airline: 'LOT',
    flight: 'LO756',
  },
  {
    id: 'id-2',
    terminal: 'A',
    localTime: '5:45',
    destination: 'Minsk',
    status: 'Landed 5:35',
    airline: 'Belavia',
    flight: 'B2848',
  },
  {
    id: 'id-3',
    terminal: 'A',
    localTime: '9:00',
    destination: 'Sharm-el-sheikh',
    status: 'Landed 9:08',
    airline: 'Bees Airlines',
    flight: 'UBE2001',
  },
];

export const arrivalsList = [
  {
    id: 'id-4',
    terminal: 'A',
    localTime: '0:55',
    destination: 'Larnaca',
    status: 'Landed 0:53',
    airline: 'Wizz Air',
    flight: 'W66260',
  },
  {
    id: 'id-5',
    terminal: 'A',
    localTime: '1:20',
    destination: 'Warsaw',
    status: 'Landed 1:35',
    airline: 'LOT',
    flight: 'LO755',
  },
  {
    id: 'id-6',
    terminal: 'D',
    localTime: '8:50',
    destination: 'Zaporizhzhia',
    status: 'Landed 8:43',
    airline: 'Motor Sich',
    flight: 'M9201',
  },
  {
    id: 'id-7',
    terminal: 'A',
    localTime: '13:25',
    destination: 'Dortmund',
    status: 'Landed 13:31',
    airline: 'Wizz Air',
    flight: 'W67301',
  },
];
